### ISSUE TITLE
rad-remote fails after an untrack --all

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/radicle-cli#189]
The expected behavior is to either list the remaining remotes, or none if they are removed.  

```
▒ rad untrack --all
ok Tracking relationships for rad:git:hnrkrjq98dyjuson9dzuu8utjawenj7x3jjsy removed

▒ rad remote
== Command failed project rad:git:hnrkrjq98dyjuson9dzuu8utjawenj7x3jjsy not found on local device
```
The root of the error is 'rad untrack --all' unexpectedly deletes the project in the monorepo in addition to untracking peers.  This is what 'rad rm' is for.

**Comment by cloudhead** [comment]
Aha, yes, `rad rm` basically calls `rad untrack --all`. We don't control this behavior. I think it *kind of* makes sense, because of you aren't tracking anyone, then there's no use for having the project anymore, though you could argue that you just never want it to be updated?

One option is to just remove the `--all` option from `rad-untrack`, as I agree it's unexpected.
