### ISSUE TITLE
Request - Change rad auth command to display name + URN

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-cli#255]
## Issue

I have multiple identities setup, such that running `rad auth` shows this:
```
(base) bordumb@bordumbs-MacBook-Pro ~ % rad auth
Your active profile is b172f291-f9ab-4990-b94e-738796026f50
  792d1c65-4dcf-4d56-b296-27446491c90d
  364755b3-e777-44c2-a040-06b595a44cbf
* b172f291-f9ab-4990-b94e-738796026f50
```

The problem is that I actually have no clue what any of these URNs are pointing to.
They aren't human readable.

## Proposal

Show both the URN and the name, such that running `rad auth` would display this:
```
(base) bordumb@bordumbs-MacBook-Pro ~ % rad auth
Your active profile is b172f291-f9ab-4990-b94e-738796026f50 (bordumb)
  792d1c65-4dcf-4d56-b296-27446491c90d (testBordumb)
  364755b3-e777-44c2-a040-06b595a44cbf (testBordumb2)
* b172f291-f9ab-4990-b94e-738796026f50 (bordumb)
```

Not too dissimilar from the way it is displayed when changing profiles:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/3743841/191134985-41ce7794-d8fc-4680-891b-aec73b34a256.png">

**Comment by bordumb** [comment]
If the URN will be displayed as output in a lot of different places:

It might make sense to abstract this into a function and have it reused everywhere.

I imagine it'll be useful to display it in a standard, human-readable way 100% of the time.

**Comment by erak** [comment]
Thanks for bringing this up! Since it's not the first time that someone mentioned this, it might be helpful to actually change it :slightly_smiling_face:.

One aspect though that needs to be considered is that `rad auth` differentiates between profiles and identities. A profile is identified by an id (e.g. `792d1c65-4dcf-4d56-b296-27446491c90d`) and an identity is identified by a URN (e.g. `rad:git:hnrk8ki4e6m8rg3p1uchue3j6zxmda1f93m6f`). The username is tied to the identity and an identity belongs to a profile.

I'm currently thinking about "hiding" the profile id or making it at least less prominent such that an altered version of your proposal would be to show the URN and the username:

```
$ rad auth

Your active identity is bordumb (rad:git:hnrk8ki4e6m8rg3p1uchue3j6zxmda1f93m6f)
  bordumb (rad:git:...)
  testBordumb2 (rad:git:...)
* testBordumb (rad:git:...)
```

**Comment by cloudhead** [comment]
I think that makes most sense. I'm thinking that in the new protocol we should do away with profiles IDs and just use the user's public key.

**Comment by erak** [comment]
Cool, after the conversation about peer IDs on Discord, I looked into this from a different angle and would propose to implement the selection like this:
```
Your active identity is hyy54y6kahwan5mh3zwx7m6hh3r1ic4xfbbao3eczuze8gtrx5apty
  hydod3x…7jrhywg (user1)
  hynddpk…uf4qwge (user2)
* hyy54y6…rx5apty (user3)
```
