### ISSUE TITLE
`rad auth` should create key and identity if profile is empty

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-cli#77]
`rad auth` should be able to handle the case where a profile including a monorepo exists but no key and local identity has been created yet. This situation occurs with Upstream at the moment. This would also guard against the case where the user aborts `rad auth` when asked to type in their passphrase.

**Comment by erak** [comment]
Hey @geigerzaehler, I will have a look and hoping to also fix #72 in one go.

**Comment by sebastinez** [comment]
Is it possible that this issue is related with #81?

**Comment by erak** [comment]
@sebastinez Yes, it is somewhat related I guess, but only in terms of handling errornous profiles. Issue #81 should not happen, whereas the empty profile created by `upstream-proxy` will be there in case the user starts up Upstream before using `rad auth` for the first time (@geigerzaehler hope to got this right though)

Since I wanted to unblock Upstream first, I decided to separate both issues for now.

**Comment by geigerzaehler** [comment]
> whereas the empty profile created by `upstream-proxy` will be there in case the user starts up Upstream before using `rad auth` for the first time (@geigerzaehler hope to got this right though)

You’re spot on
